name: GhostScript

on:
  workflow_dispatch:

jobs:
  compress-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install GhostScript
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript

      - name: version
        run: |
          gs --version

      - name: compress
        run: | 
          mkdir compress
          files=(`ls -1 ./download`)
          for file_name in "${files[@]}"; do
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=./compress/${file_name} ${file_name}
          done

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compress
          path: compress/
          retention-days: 30
