name: Run workflow on label

on:
  issues:
    types:
      - labeled

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check for specific label
        if: contains(github.event.label.name, 'your-label')
        run: echo "Label 'your-label' was added to the issue."