name: test_workflow

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Deploy target
        options:
          - mock
          - staging
          - production

jobs:
  build_ios:
    runs-on: macos-13
    strategy:
      matrix:
        branch:
          - ${{ github.ref_name }}
      fail-fast: false
    defaults:
      run:
        working-directory: user
    steps:
      - name: Checkout (${{ github.ref_name }})
        uses: actions/checkout@v3
